version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: arc-webserver
    volumes:
     - ./ARC:/application
     - ./server-conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8081:80"

  php-fpm:
    image: shanoogs/reepsplus_php-fpm
    container_name: arc-php-fpm
    working_dir: /application
    volumes:
      - ./ARC:/application
      - D:/properties/DBProperties:/database
  
  postgre:
    container_name: arc-postgres_db
    image: postgres:9.6.3-alpine
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: password1
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: arc-pgadmin4
    ports:
      - 8086:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    links:
      - "postgre"

volumes:
  db:
